[package]
name = "lovelace"
version = "0.1.0"
edition = "2021"

[dependencies]
im-rc = "15.1.0"
petgraph = "0.6.5"
tokio = { version = "1.38.0", features = [
  "io-std",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
] }
tower-lsp = "0.20.0"
