[package]
name = "firefly"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = [
  "io-std",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
] }
tower-lsp = "0.20.0"
